bank/template/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls")),             # UI Kits Html files
    path('', include('admin_soft.urls')),
]

bank/urls.py
from django.urls import path
from . import views
app_name = 'bank'
urlpatterns = [
    path('dashboard/', views.index_views, name='home'),
    path('applications/<int:user_id>/', views.show_applications, name='apply'),
    path('topup/<int:user_id>', views.topup, name='topup'),
    path('create/<int:user_id>', views.create_transaction, name='create'),
    path('login/', views.login_bank_admin, name="login"),
    path('register', views.register_user, name="register")
]

seller/urls.py
from django.urls import path
from . import views
app_name = 'seller'

urlpatterns = [
    path('dashboard/', views.show_dashboard, name='dashboard'),
    path('products/', views.show_products, name='products'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products/update/<int:product_id>/', views.update_product, name='product_update_seller'),
    path('delete_product/<int:product_id>', views.delete_product, name='delete_product_seller'),
    path('transactions/', views.show_transactions, name='transactions'),
    path('transactions/update/<int:transaction_id>/', views.transaction_detail, name='transaction_update'),
    path('transactions/<int:transaction_id>/', views.transaction_detail, name='transaction_detail'),
    
    path('delete_transaction/', views.delete_transaction, name='delete_transaction'),
    path('create_transaction/', views.create_transaction, name='create_transaction'),
    path('create_product/', views.create_product, name='create_product'),
    path('get_product/', views.get_product, name='get_product'),

        # Auth 
    path('register/', views.register_seller, name='register_seller'),
    path('login/', views.login_seller, name='login_seller'),
    path('logout/', views.logout_seller, name='logout_seller'),
]

wrpl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ecoms/', include('ecoms.urls', namespace='buyer')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('delivery/', include('delivery.urls')),
    path('bank/', include('bank.urls')),
    path('seller/', include('seller.urls', namespace='seller')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    no_telp = models.CharField(max_length=32)
    location = models.CharField(max_length=200)
    no_rek = models.CharField(max_length=100)
    
    # def __str__(self):
    #     return f'{self.user.email} - {self.user.username}'


class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100)
    product_description = models.CharField(max_length=100)
    product_category = models.CharField(max_length=100, default='lainnya')
    product_price = models.IntegerField()
    stock_gudang = models.IntegerField()
    product_image = models.ImageField(upload_to='product_images', default='default_product.jpg')
    supplier = models.CharField(max_length=100 , default='none')
    
    def __str__(self):
        return f'{self.product_name} - {self.product_price}'

class Transaction(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    buyer = models.CharField(max_length=100)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    total_price = models.IntegerField()
    transaction_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=32, default='pending')
    
    def __str__(self):
        return f'{self.product_name} - {self.buyer}'

seller/views.py
from django.shortcuts import (
    render,
    redirect
)
from django.http import JsonResponse
from django.contrib import messages
from .models import *
from supplier.models import Product as ProductSupplier, Supplier
from django.contrib.auth import (
    authenticate,
    login,
    logout
)
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import (
    csrf_protect,
    csrf_exempt
)
from django.core.paginator import Paginator
from django.utils import timezone
from django.urls import reverse

def register_seller(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        location = request.POST.get('address')
        no_telp = request.POST.get('phone')
        no_rek = request.POST.get('no_rek')
        print(username, password, email, location, no_telp, no_rek)
        
        if not (username and password and email and location and no_telp and no_rek):
            messages.error(request, "Please fill out all fields.")
            return render(request, 'seller/home/register.html')
        try:
            user = User.objects.create_user(
                username=username, password=password, email=email)
            seller = Seller(
                user=user, no_telp=no_telp, location=location, no_rek=no_rek)
            
            if user.last_login is None:
                 user.last_login = timezone.now()
            user.save(using='seller_db')
            seller.save(using='seller_db')
            messages.success(request, "User registered succesfully")
            login(request, user)
            return redirect('/seller/dashboard')
        except Exception as e:
            print("error",e)
            messages.error(request, "Failed to register user.")
    return render(request, 'register_seller.html', {})


def login_seller(request):
    
    print("login seller")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        print(username, password)
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            print("sukses auth")
            login(request, user)
            messages.success(request, f"Hi {username}")
            print("Redirecting to /seller/dashboard/") 
            return redirect(reverse('seller:dashboard'))
    return render(request, 'login_seller.html')

@login_required(login_url="/seller/login")
def create_product(request):
    product_name = request.POST.get("nama-produk")
    product_description = request.POST.get("deskripsi-produk")
    stock_gudang = request.POST.get("stock-gudang")
    product_price = request.POST.get("harga-produk")
    user = User.objects.using('seller_db').filter(id=request.user.id)
    seller = Seller.objects.filter(user=user)
    product = Product(seller=seller, product_name=product_name,
                      product_description=product_description, stock_gudang=stock_gudang, product_price=product_price)
    product.save(using='seller_db')
    return render(request, 'create_product.html')


@login_required(login_url="/seller/login")
def get_product(request):
    user = User.objects.using('seller_db').get(id=request.user.id)
    seller = Seller.objects.using('seller_db').get(user=user)
    suppliers = Supplier.objects.using('supplier_db').all()
    products = None
    product = None
    
    if request.method == "POST":
        id_supplier = request.POST.get("supplier_id")
      
        supplier = Supplier.objects.using('supplier_db').filter(id=id_supplier).first()
       
        if id_supplier : 
            try:
                products = ProductSupplier.objects.using('supplier_db').filter(supplier=supplier)
            except ProductSupplier.DoesNotExist:
                products = None
        if request.POST.get("qty") is not None:
            qty = int(request.POST.get("qty"))
            product_id = request.POST.get("product_id")
            prod = ProductSupplier.objects.using('supplier_db').filter(id=product_id).first()
            if qty > prod.stock_gudang:
                messages.error(request, "Stock not enough")
                print("stock not enough")
                return render(request, 'get_product.html', {'suppliers': suppliers, 'products': products})
            else:
                if Product.objects.using('seller_db').filter(product_name=prod.product_name).exists():
                    product = Product.objects.using('seller_db').filter(product_name=prod.product_name).first()
                    product.stock_gudang += qty
                    product.save(using='seller_db')
                    prod.stock_gudang -= qty
                    prod.save(using='supplier_db')
                    messages.success(request, "Product added successfully")
                    return redirect('/seller/dashboard')
                else:
                    product_seller = Product(seller=seller, product_name=prod.product_name,
                                      product_description=prod.product_description, product_category=prod.product_category,  product_price=prod.product_price,stock_gudang=qty, supplier=prod.supplier.user.username)
                    prod.stock_gudang -= qty
                    product_seller.save(using='seller_db')
                    prod.save(using='supplier_db')
                    messages.success(request, "Product added successfully")
                    return redirect('/seller/dashboard')
    content = {
        'suppliers': suppliers,
        'products': products,
    }
    return render(request, 'get_product.html', content)

@login_required(login_url="/seller/login")
def create_transaction(request):
    product = request.POST.get("id-product")
    buyer = request.POST.get("buyer")
    quantity = request.POST.get("quantity")
    total_price = request.POST.get("total-price")
    transaction_date = request.POST.get("transaction-date")
    status = request.POST.get("status")
    user = User.objects.using('seller_db').filter(id=request.user.id)
    seller = Seller.objects.filter(user=user)
    product = Transaction(seller = seller, product=product, buyer = buyer, quantity=quantity, total_price=total_price, transaction_date=transaction_date, status=status)
    product.save(using='seller_db')
    return render(request, 'create_transaction.html')

@login_required(login_url="/seller/login")
def show_products(request):
    products = Product.objects.using('seller_db').all()
    return render(request, 'products.html', {'products': products})

@login_required(login_url="/seller/login")
def show_transactions(request):
    transactions = Transaction.objects.using('seller_db').all()
    return render(request, 'transactions.html', {'transactions': transactions})

@login_required(login_url="/seller/login")
def product_detail(request, product_id):
    product = Product.objects.using('seller_db').filter(id=product_id)
    return render(request, 'product_detail.html', {'product': product})
    
@login_required(login_url="/seller/login")
def transaction_detail(request, transaction_id):
    transaction = Transaction.objects.using('seller_db').filter(id=transaction_id)
    return render(request, 'transaction_detail.html', {'transaction': transaction})

@login_required(login_url="/seller/login")
def update_product(request, product_id):
    # try:
    user = User.objects.get(id=request.user.id)
    product = Product.objects.using('seller_db').get(id=product_id)
    seller = Seller.objects.using(
        'seller_db').get(user_id=user.id)
    
    if request.method == "POST":

        product.product_name = request.POST.get("product_name")
        product.product_description = request.POST.get("product_description")
        product.product_category = request.POST.get("product_category")
        product.stock_gudang = request.POST.get("stock_gudang")
        product.product_price = request.POST.get("product_price")
        if request.FILES["product_image"] is not None:
            product.product_image = request.FILES["product_image"]
        product.save(using="seller_db")  # update product
        products = Product.objects.using(
            'seller_db').filter(seller = seller,)

        # paginator = Paginator(products, 10)  # 10 products per page
        # page_number = request.POST.get("page")
        # page_obj = paginator.get_page(page_number)
        # return render(request, 'tables_dashboard.html', {'page_obj': page_obj})
        return redirect("/seller/dashboard")
    return render(request, 'update_product_seller.html', {"product": product})

@login_required(login_url="/seller/login")
def update_transaction(request, transaction_id):
    # try:
    user = User.objects.get(id=request.user.id)
    transaction = Transaction.objects.using('seller_db').get(id=transaction_id)
    seller = Seller.objects.using(
        'seller_db').get(user_id=user.id)
    if request.method == "POST":

        transaction.product = request.POST.get("id-product")
        transaction.buyer = request.POST.get("buyer")
        transaction.quantity = request.POST.get("quantity")
        transaction.total_price = request.POST.get("total-price")
        transaction.transaction_date = request.POST.get("transaction-date")
        transaction.status = request.POST.get("status")
        transaction.save(using="seller_db")  # update product
        transactions = Product.objects.using(
            'seller_db').filter(seller = seller,)

        paginator = Paginator(transactions, 10)  # 10 products per page
        page_number = request.POST.get("page")
        page_obj = paginator.get_page(page_number)
        return render(request, 'home/tables.html', {'page_obj': page_obj})
    return render(request, 'home/update_transaction.html', {"transaction": transaction})

@login_required(login_url="/seller/login")

seller/templates/get_product.html
{% extends 'base/base-fullscreen.html' %}

{% block title %} Register {% endblock title %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<!-- Page content -->
<div class="container mt--8 pb-5">
  <div class="d-flex">
    
  </div>
  <!-- Table -->
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8">
      <div class="card bg-secondary border-0">
        <div class="card-header bg-transparent pb-5">
          <div class="card-body px-lg-5 py-lg-5">
            {% comment %} <form role="form" action="{% url 'seller:get_product' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <div class="input-group nput-group-merge input-group-alternative mb-3">
                  <label class="input-group-text" for="inputGroupSelect02">Supplier</label>
                  <select class="form-select w-75 border-0 bg-neutral text-gray" id="inputGroupSelect02" name="supplier_id" >
                    {% for supplier in  suppliers %}
                    <option value="{{ supplier.id }}">{{supplier}}</option>
                    {% endfor %}
                  </select>
                  <button type="submit" class="">Search</button>
                </div>
              </div>
            </form> {% endcomment %}

            
            <form role="form" action="{% url 'seller:get_product' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <div class="input-group nput-group-merge input-group-alternative mb-3">
                  <label class="input-group-text" for="inputGroupSelect02">Supplier</label>
                  <select class="form-select w-75 border-0 bg-neutral text-gray" id="inputGroupSelect02" name="supplier_id" onchange="this.form.submit()">
                    {% for supplier in  suppliers %}
                    <option value="{{ supplier.id }}">{{supplier}}</option>
                    {% endfor %}
                  </select>
                </div>
              </div>

              {% if products %}
              <div class="form-group">
                <div class="input-group nput-group-merge input-group-alternative mb-3">
                  <label class="input-group-text" for="product_id">Name Product</label>
                  <select class="form-select w-50 border-0 bg-neutral text-gray" id="product_id" name="product_id" >
                    {% for product in  products %}
                    <option value="{{ product.id }}">{{product.product_name}} - {{product.stock_gudang}}pcs</option>
                    {% endfor %}
                  </select>
                </div>
              </div>
                <div class="form-group">
                  <div class="input-group input-group-merge input-group-alternative mb-3">
                    <input class="form-control" placeholder="qty" type="number" id="qty"
                      name="qty" required>
                  </div>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-primary mt-4">Create Product</button>
                </div>
              </div>
              {% endif %}
            </form>
            
           
          </div>
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}

  <!-- Specific JS goes HERE -->
  {% block javascripts %}{% endblock javascripts %}

seller/templates/login_seller.html
{% extends 'base/base-fullscreen.html' %}

<!-- Specific CSS goes HERE -->
{% block stylesheets %}{% endblock stylesheets %} {% block content %}

<!-- Page content -->
<div class="container mt--8 pb-5">
  <div class="row justify-content-center">
    <div class="col-lg-5 col-md-7">
      <div class="card bg-secondary border-0 mb-0">
        <div class="card-body px-lg-5 py-lg-5">
          <div class="text-center text-muted mb-4">
            <small>sign in with credentials</small>
          </div>
          <form
            role="form"
            action="{% url 'seller:login_seller' %}"
            method="post"
          >
            {% csrf_token %}
            <div class="form-group mb-3">
              <div
                class="input-group input-group-merge input-group-alternative"
              >
                <div class="input-group-prepend">
                  <span class="input-group-text"
                    ><i class="ni ni-email-83"></i
                  ></span>
                </div>
                <input
                  class="form-control"
                  placeholder="username"
                  type="text"
                  id="username"
                  name="username"
                />
              </div>
            </div>
            <div class="form-group">
              <div
                class="input-group input-group-merge input-group-alternative"
              >
                <div class="input-group-prepend">
                  <span class="input-group-text"
                    ><i class="ni ni-lock-circle-open"></i
                  ></span>
                </div>
                <input
                  class="form-control"
                  placeholder="Password"
                  type="password"
                  id="password"
                  name="password"
                />
              </div>
            </div>
            <div
              class="custom-control custom-control-alternative custom-checkbox"
            >
              <input
                class="custom-control-input"
                id=" customCheckLogin"
                type="checkbox"
              />
              <label class="custom-control-label" for=" customCheckLogin">
                <span class="text-muted">Remember me</span>
              </label>
            </div>
            <div class="text-center">
              <button type="submit" class="btn btn-primary my-4">
                Sign in
              </button>
            </div>
          </form>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-6">
          <a href="{% url 'seller:register_seller' %}" class="text-light"
            ><small>Create Account</small></a
          >
        </div>
        <div class="col-6 text-right">
          <a href="https://appseed.us?ref=j2-argon-demo" class="text-light"
            ><small>Get Support</small></a
          >
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

seller/templates/tables_dashboard.html
{% extends 'base/base.html' %}
{% load custom_tags %}
{% block title %} Tables {% endblock title %}

{% block content %}

<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">Tables</h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item"><a href="#">Tables</a></li>
              <li class="breadcrumb-item active" aria-current="page">Tables</li>
            </ol>
          </nav>
        </div>
        <div class="col-lg-6 col-5 text-right">
          <a href="{% url 'seller:get_product' %}" class="btn btn-sm btn-neutral">Get Product</a>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card">
        <!-- Card header -->
        <div class="card-header border-0">
          <h3 class="mb-0">Product table</h3>
        </div>
        <!-- Light table -->
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col" class="sort" data-sort="name">Name</th>
                <th scope="col" class="sort" data-sort="budget">Description</th>
                <th scope="col" class="sort" data-sort="status">Stok</th>
                <th scope="col" class="sort" data-sort="status">Category</th>
                <th scope="col" class="sort" data-sort="status">Price</th>
                <th scope="col">Supplier</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody class="list">
              {% for product in page_obj %}
              <tr>
                <th scope="row">
                  <div class="media align-items-center">
                    <a href="#" class="avatar rounded-circle mr-3">
                      {% comment %} <img alt="Image placeholder" id="product-image-{{ forloop.counter }}" src="{% random_image %}"> {% endcomment %}
                      <img src="{{ product.product_image.url }}" alt="">
                    </a>
                    <div class="media-body">
                      <span class="name mb-0 text-sm">{{product.product_name}}</span>
                    </div>
                  </div>
                </th>
                <td class="budget">
                  {{product.product_description}}
                </td>
                <td>
                  <span class="badge badge-dot mr-4">
                    <i class="bg-warning"></i>
                    <span class="status">{{product.stock_gudang}}</span>
                  </span>
                </td>


                <td class="budget">
                  {{product.product_category}}
                </td>

                <td class="budget">
                  {{product.product_price}}
                </td>

                <td class="budget">
                  {{product.supplier}}
                </td>

                <td class="text-right">
                  <div class="dropdown">
                    <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown"
                      aria-haspopup="true" aria-expanded="false">
                      <i class="fas fa-ellipsis-v"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                      <a class="dropdown-item"
                        href="{% url 'seller:product_update_seller' product_id=product.id %}">Update</a>
                      <a class="dropdown-item" href="{% url 'seller:delete_product_seller' product_id=product.id %}">Delete
                        action</a>
                      <a class="dropdown-item" href="#">Send Product to Ecommerce Warehouse</a>
                    </div>
                  </div>
                </td>
              </tr>
              {% endfor %}
              {% comment %} end row table {% endcomment %}

            </tbody>
          </table>
        </div>
        <!-- Card footer -->
        <div class="card-footer py-4">
          <nav aria-label="...">
            <ul class="pagination justify-content-end mb-0">
              <li class="page-item {% if page_obj.has_previous %} {% else %} disabled {% endif %}">
                <a class="page-link"
                  href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% endif %}"
                  tabindex="-1">
                  <i class="fas fa-angle-left"></i>
                  <span class="sr-only">Previous</span>
                </a>
              </li>
              {% for num in page_obj.paginator.page_range %}
              {% if page_obj.number == num %}
              <li class="page-item active">
                <a class="page-link" href="#">{{ num }}</a>
              </li>
              {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ num }}">{{ num }}</a>
              </li>
              {% endif %}
              {% endfor %}
              <li class="page-item {% if page_obj.has_next %} {% else %} disabled {% endif %}">
                <a class="page-link" href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% endif %}">
                  <i class="fas fa-angle-right"></i>
                  <span class="sr-only">Next</span>
                </a>
              </li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>

  </tbody>
  </table>
</div>
</div>
</div>
</div>

{% include "includes/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}