bank/template/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls")),             # UI Kits Html files
    path('', include('admin_soft.urls')),
]

bank/urls.py
from django.urls import path
from . import views
app_name = 'bank'
urlpatterns = [
    path('dashboard/', views.index_views, name='home'),
    path('applications/<int:user_id>/', views.show_applications, name='apply'),
    path('topup/<int:user_id>', views.topup, name='topup'),
    path('create/<int:user_id>', views.create_transaction, name='create'),
    path('login/', views.login_bank_admin, name="login"),
    path('register', views.register_user, name="register")
]

seller/urls.py
from django.urls import path
from . import views
app_name = 'seller'

urlpatterns = [
    path('dashboard/', views.show_dashboard, name='dashboard'),
    path('products/', views.show_products, name='products'),
    path('products/<int:product_id>/', views.product_detail, name='product_detail'),
    path('products/update/<int:product_id>/', views.update_product, name='product_update_seller'),
    path('delete_product/<int:product_id>', views.delete_product, name='delete_product_seller'),
    path('transactions/', views.show_transactions, name='transactions'),
    path('transactions/update/<int:transaction_id>/', views.transaction_detail, name='transaction_update'),
    path('transactions/<int:transaction_id>/', views.transaction_detail, name='transaction_detail'),
    
    path('delete_transaction/', views.delete_transaction, name='delete_transaction'),
    path('create_transaction/', views.create_transaction, name='create_transaction'),
    path('create_product/', views.create_product, name='create_product'),
    path('get_product/', views.get_product, name='get_product'),

        # Auth 
    path('register/', views.register_seller, name='register_seller'),
    path('login/', views.login_seller, name='login_seller'),
    path('logout/', views.logout_seller, name='logout_seller'),
]

supplier/urls.py
from django.urls import path
from . import views
app_name = 'supplier'
urlpatterns = [
    # path('/'),
    path('registersupplier/', views.registersupplier, name='registersupplier'),
    path('login/', views.login_supplier, name='login_supplier'),
    path('dashboard/', views.show_dashboard, name='dashboard'),
    path('product/create/', views.create_product, name='create_product'),
    path('product/update/<int:product_id>',
         views.update_product, name='update_product'),
    path('product/delete/<int:product_id>',
         views.delete_product, name='delete_product'),
    path('logout/', views.logout_supplier, name='logout_supplier'),
    path('seller_request/', views.accept_seller_request, name='seller_request')
]

wrpl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ecoms/', include('ecoms.urls', namespace='buyer')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('delivery/', include('delivery.urls')),
    path('bank/', include('bank.urls')),
    path('seller/', include('seller.urls', namespace='seller')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

seller/models.py
from typing import Any
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Seller(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    no_telp = models.CharField(max_length=32)
    location = models.CharField(max_length=200)
    no_rek = models.CharField(max_length=100)
    
    # def __str__(self):
    #     return f'{self.user.email} - {self.user.username}'


class Product(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=100)
    product_description = models.CharField(max_length=100)
    product_category = models.CharField(max_length=100, default='lainnya')
    product_price = models.IntegerField()
    stock_gudang = models.IntegerField()
    product_image = models.ImageField(upload_to='product_images', default='default_product.jpg')
    supplier = models.CharField(max_length=100 , default='none')
    
    def __str__(self):
        return f'{self.product_name} - {self.product_price}'

class Transaction(models.Model):
    seller = models.ForeignKey(Seller, on_delete=models.CASCADE)
    buyer = models.CharField(max_length=100)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    total_price = models.IntegerField()
    transaction_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=32, default='pending')
    
    def __str__(self):
        return f'{self.product_name} - {self.buyer}'

seller/views.py
from django.shortcuts import (
    render,
    redirect
)
from django.http import JsonResponse
from django.contrib import messages
from .models import *
from supplier.models import Product as ProductSupplier, Supplier
from django.contrib.auth import (
    authenticate,
    login,
    logout
)
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import (
    csrf_protect,
    csrf_exempt
)
from django.core.paginator import Paginator
from django.utils import timezone
from django.urls import reverse

def register_seller(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        location = request.POST.get('address')
        no_telp = request.POST.get('phone')
        no_rek = request.POST.get('no_rek')
        print(username, password, email, location, no_telp, no_rek)
        
        if not (username and password and email and location and no_telp and no_rek):
            messages.error(request, "Please fill out all fields.")
            return render(request, 'seller/home/register.html')
        try:
            user = User.objects.create_user(
                username=username, password=password, email=email)
            seller = Seller(
                user=user, no_telp=no_telp, location=location, no_rek=no_rek)
            
            if user.last_login is None:
                 user.last_login = timezone.now()
            user.save(using='seller_db')
            seller.save(using='seller_db')
            messages.success(request, "User registered succesfully")
            login(request, user)
            return redirect('/seller/dashboard')
        except Exception as e:
            print("error",e)
            messages.error(request, "Failed to register user.")
    return render(request, 'register_seller.html', {})


def login_seller(request):
    
    print("login seller")
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        print(username, password)
        user = authenticate(request, username=username, password=password)
        print(user)
        if user is not None:
            print("sukses auth")
            login(request, user)
            messages.success(request, f"Hi {username}")
            print("Redirecting to /seller/dashboard/") 
            return redirect(reverse('seller:dashboard'))
    return render(request, 'login_seller.html')

@login_required(login_url="/seller/login")
def create_product(request):
    product_name = request.POST.get("nama-produk")
    product_description = request.POST.get("deskripsi-produk")
    stock_gudang = request.POST.get("stock-gudang")
    product_price = request.POST.get("harga-produk")
    user = User.objects.using('seller_db').filter(id=request.user.id)
    seller = Seller.objects.filter(user=user)
    product = Product(seller=seller, product_name=product_name,
                      product_description=product_description, stock_gudang=stock_gudang, product_price=product_price)
    product.save(using='seller_db')
    return render(request, 'create_product.html')


@login_required(login_url="/seller/login")
def get_product(request):
    user = User.objects.using('seller_db').get(id=request.user.id)
    seller = Seller.objects.using('seller_db').get(user=user)
    suppliers = Supplier.objects.using('supplier_db').all()
    products = None
    product = None
    
    if request.method == "POST":
        id_supplier = request.POST.get("supplier_id")
      
        supplier = Supplier.objects.using('supplier_db').filter(id=id_supplier).first()
       
        if id_supplier : 
            try:
                products = ProductSupplier.objects.using('supplier_db').filter(supplier=supplier)
            except ProductSupplier.DoesNotExist:
                products = None
        if request.POST.get("qty") is not None:
            qty = int(request.POST.get("qty"))
            product_id = request.POST.get("product_id")
            prod = ProductSupplier.objects.using('supplier_db').filter(id=product_id).first()
            if qty > prod.stock_gudang:
                messages.error(request, "Stock not enough")
                print("stock not enough")
                return render(request, 'get_product.html', {'suppliers': suppliers, 'products': products})
            else:
                if Product.objects.using('seller_db').filter(product_name=prod.product_name).exists():
                    product = Product.objects.using('seller_db').filter(product_name=prod.product_name).first()
                    product.stock_gudang += qty
                    product.save(using='seller_db')
                    prod.stock_gudang -= qty
                    prod.save(using='supplier_db')
                    messages.success(request, "Product added successfully")
                    return redirect('/seller/dashboard')
                else:
                    product_seller = Product(seller=seller, product_name=prod.product_name,
                                      product_description=prod.product_description, product_category=prod.product_category,  product_price=prod.product_price,stock_gudang=qty, supplier=prod.supplier.user.username)
                    prod.stock_gudang -= qty
                    product_seller.save(using='seller_db')
                    prod.save(using='supplier_db')
                    messages.success(request, "Product added successfully")
                    return redirect('/seller/dashboard')
    content = {
        'suppliers': suppliers,
        'products': products,
    }
    return render(request, 'get_product.html', content)

@login_required(login_url="/seller/login")
def create_transaction(request):
    product = request.POST.get("id-product")
    buyer = request.POST.get("buyer")
    quantity = request.POST.get("quantity")
    total_price = request.POST.get("total-price")
    transaction_date = request.POST.get("transaction-date")
    status = request.POST.get("status")
    user = User.objects.using('seller_db').filter(id=request.user.id)
    seller = Seller.objects.filter(user=user)
    product = Transaction(seller = seller, product=product, buyer = buyer, quantity=quantity, total_price=total_price, transaction_date=transaction_date, status=status)
    product.save(using='seller_db')
    return render(request, 'create_transaction.html')

@login_required(login_url="/seller/login")
def show_products(request):
    products = Product.objects.using('seller_db').all()
    return render(request, 'products.html', {'products': products})

@login_required(login_url="/seller/login")
def show_transactions(request):
    transactions = Transaction.objects.using('seller_db').all()
    return render(request, 'transactions.html', {'transactions': transactions})

@login_required(login_url="/seller/login")
def product_detail(request, product_id):
    product = Product.objects.using('seller_db').filter(id=product_id)
    return render(request, 'product_detail.html', {'product': product})
    
@login_required(login_url="/seller/login")
def transaction_detail(request, transaction_id):
    transaction = Transaction.objects.using('seller_db').filter(id=transaction_id)
    return render(request, 'transaction_detail.html', {'transaction': transaction})

@login_required(login_url="/seller/login")
def update_product(request, product_id):
    # try:
    user = User.objects.get(id=request.user.id)
    product = Product.objects.using('seller_db').get(id=product_id)
    seller = Seller.objects.using(
        'seller_db').get(user_id=user.id)
    
    if request.method == "POST":

        product.product_name = request.POST.get("product_name")
        product.product_description = request.POST.get("product_description")
        product.product_category = request.POST.get("product_category")
        product.stock_gudang = request.POST.get("stock_gudang")
        product.product_price = request.POST.get("product_price")
        if request.FILES["product_image"] is not None:
            product.product_image = request.FILES["product_image"]
        product.save(using="seller_db")  # update product
        products = Product.objects.using(
            'seller_db').filter(seller = seller,)

        # paginator = Paginator(products, 10)  # 10 products per page
        # page_number = request.POST.get("page")
        # page_obj = paginator.get_page(page_number)
        # return render(request, 'tables_dashboard.html', {'page_obj': page_obj})
        return redirect("/seller/dashboard")
    return render(request, 'update_product_seller.html', {"product": product})

@login_required(login_url="/seller/login")
def update_transaction(request, transaction_id):
    # try:
    user = User.objects.get(id=request.user.id)
    transaction = Transaction.objects.using('seller_db').get(id=transaction_id)
    seller = Seller.objects.using(
        'seller_db').get(user_id=user.id)
    if request.method == "POST":

        transaction.product = request.POST.get("id-product")
        transaction.buyer = request.POST.get("buyer")
        transaction.quantity = request.POST.get("quantity")
        transaction.total_price = request.POST.get("total-price")
        transaction.transaction_date = request.POST.get("transaction-date")
        transaction.status = request.POST.get("status")
        transaction.save(using="seller_db")  # update product
        transactions = Product.objects.using(
            'seller_db').filter(seller = seller,)

        paginator = Paginator(transactions, 10)  # 10 products per page
        page_number = request.POST.get("page")
        page_obj = paginator.get_page(page_number)
        return render(request, 'home/tables.html', {'page_obj': page_obj})
    return render(request, 'home/update_transaction.html', {"transaction": transaction})

@login_required(login_url="/seller/login")

seller/templates/components/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a href="https://appseed.us/admin-dashboards/django" 
                 class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="https://bit.ly/3fKQZaL" 
                 class="font-weight-bold ml-1" target="_blank"> &copy; Creative-Tim</a> 
                 - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div>
      </footer>

seller/templates/components/navigation-fullscreen.html
<nav
  id="navbar-main"
  class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light"
>
  <div class="container">
    <a class="navbar-brand" href="/"> Lahh 2.0 Store </a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbar-collapse"
      aria-controls="navbar-collapse"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div
      class="navbar-collapse navbar-custom-collapse collapse"
      id="navbar-collapse"
    >
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="/static/assets/img/brand/blue.png" />
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button
              type="button"
              class="navbar-toggler"
              data-toggle="collapse"
              data-target="#navbar-collapse"
              aria-controls="navbar-collapse"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          {% comment %} "../home/login.ht" {% endcomment %}
          <a href="{% url 'supplier:login_supplier'  %}" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'supplier:registersupplier' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
    </div>
  </div>
</nav>

seller/templates/components/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      <form action="{% url 'supplier:dashboard' %}" method=POST class="navbar-search navbar-search-light form-inline mr-sm-3" id="navbar-search-main">
        {% csrf_token %} 
        <div class="form-group mb-0">
          <div class="input-group input-group-alternative input-group-merge">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-search"></i></span>
            </div>
            <input class="form-control" placeholder="Search" type="text" name="search" >
            <input class="btn btn-outline-secondary" type="submit" value="Search">
          </div>
        </div>
        <button type="button" class="close" data-action="search-close" data-target="#navbar-search-main" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </form>
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
            <!-- Dropdown header -->
            <div class="px-3 py-3">
              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">13</strong> notifications.</h6>
            </div>
            <!-- List group -->
            <div class="list-group list-group-flush">
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-1.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-2.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-3.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>5 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Your posts have been liked a lot.</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>2 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Let's meet at Starbucks at 11:30. Wdyt?</p>
                  </div>
                </div>
              </a>
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-5.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">John Snow</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>3 hrs ago</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">A new issue has been reported for Argon.</p>
                  </div>
                </div>
              </a>
            </div>
            <!-- View all -->
            <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
            <div class="row shortcuts px-4">
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
                <small>Calendar</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-email-83"></i>
                </span>
                <small>Email</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                  <i class="ni ni-credit-card"></i>
                </span>
                <small>Payments</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                  <i class="ni ni-books"></i>
                </span>
                <small>Reports</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                  <i class="ni ni-pin-3"></i>
                </span>
                <small>Maps</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">
                  <i class="ni ni-basket"></i>
                </span>
                <small>Shop</small>
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="/profile.html" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a target="_blank" href="http://appseed.us/support" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'logout' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

seller/templates/components/sidenav.html
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="/">
        <h1>Lahh 2.0 Store</h1>
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="/">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Dashboard</span>
            </a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link {% if 'profile' in segment %} active {% endif %}" href="/profile.html">
              <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text">Profile</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'tables' in segment %} active {% endif %}" href="{% url 'supplier:dashboard' %}" >
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">Products</span>
            </a>
          </li>
         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
              <i class="ni ni-user-run text-red"></i>
              <span class="nav-link-text">Logout</span>
            </a>
          </li>            
        </ul>
        <!-- Divider -->
        <hr class="my-3">
        <!-- Heading -->
       

          

         

          
        </ul>
      </div>
    </div>
  </div>
</nav>