bank/template/apps/home/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.urls import path, re_path
from apps.home import views

urlpatterns = [

    # The home page
    path('', views.index, name='home'),

    # Matches any html file
    re_path(r'^.*\.*', views.pages, name='pages'),

]

bank/template/core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register
    path("", include("apps.home.urls")),             # UI Kits Html files
    path('', include('admin_soft.urls')),
]

bank/urls.py
from django.urls import path
from . import views
app_name = 'bank'
urlpatterns = [
    path('dashboard/', views.index_views, name='home'),
    path('applications/<int:user_id>/', views.show_applications, name='apply'),
    path('topup/<int:user_id>', views.topup, name='topup'),
    path('create/<int:user_id>', views.create_transaction, name='create'),
    path('login/', views.login_bank_admin, name="login"),
    path('register', views.register_user, name="register")
]

wrpl/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('ecoms/', include('ecoms.urls', namespace='buyer')),
    path('supplier/', include('supplier.urls', namespace='supplier')),
    path('delivery/', include('delivery.urls')),
    path('bank/', include('bank.urls')),
    path('seller/', include('seller.urls', namespace='seller')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bank/models.py
from django import forms
from django.utils import timezone
from django.db import models
import uuid
from django.contrib.auth.models import User

def upload_to(instance, filename):
    return 'ktp_photos/%s/%s' % (instance.name, filename)

class BankAccount(models.Model):
    user_id = models.IntegerField(default=0)
    name = models.CharField(max_length=200)
    bank_number = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, primary_key=True)
    ktp_photo = models.ImageField(upload_to=upload_to, blank=True, null=True)
    balance = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.name} - {self.bank_number}'

class Application(models.Model):
    STATUS_CHOICES = (
        ('P', 'Pending'),
        ('A', 'Accepted'),
        ('D', 'Declined'),
    )

    name = models.CharField(max_length=200, default='')
    ktp_photo = models.ImageField(upload_to=upload_to, blank=True, null=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default='P')
    applied_at = models.DateTimeField(default=timezone.now)
    bank_account = models.OneToOneField(BankAccount, on_delete=models.CASCADE, null=True, blank=True)
    user_id = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.name} - {self.get_status_display()}'
    

class BankAdmin(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return f'{self.user.username}'
    

class TransactionHistory(models.Model):
    TRANSACTION_TYPES = (
        ('D', 'Deposit'),
        ('W', 'Withdrawal'),
        ('P', 'Purchase'),
    )

    source_account = models.ForeignKey('BankAccount', on_delete=models.CASCADE, related_name='outgoing_transactions', default=0)
    destination_account = models.ForeignKey('BankAccount', on_delete=models.CASCADE, related_name='incoming_transactions', default=0)
    transaction_type = models.CharField(max_length=1, choices=TRANSACTION_TYPES)
    amount = models.DecimalField(max_digits=10, decimal_places=2) 
    transaction_date = models.DateTimeField(auto_now_add=True) 

    def __str__(self):
        return f'Transaction from account {self.source_account_id}'
    

bank/template/apps/authentication/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models

# Create your models here.

bank/template/apps/home/models.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.db import models
from django.contrib.auth.models import User

# Create your models here.

bank/forms.py
from django import forms
from .models import Application

class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['name', 'ktp_photo']

bank/template/apps/authentication/forms.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

bank/template/apps/authentication/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

# Create your views here.
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import LoginForm, SignUpForm


def login_view(request):
    form = LoginForm(request.POST or None)

    msg = None

    if request.method == "POST":

        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("/")
            else:
                msg = 'Invalid credentials'
        else:
            msg = 'Error validating the form'

    return render(request, "accounts/login.html", {"form": form, "msg": msg})


def register_user(request):
    msg = None
    success = False

    if request.method == "POST":
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = 'User created - please <a href="/login">login</a>.'
            success = True

            # return redirect("/login/")

        else:
            msg = 'Form is not valid'
    else:
        form = SignUpForm()

    return render(request, "accounts/register.html", {"form": form, "msg": msg, "success": success})

bank/template/apps/home/views.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django import template
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse


@login_required(login_url="/login/")
def index(request):
    context = {'segment': 'index'}

    html_template = loader.get_template('home/index.html')
    return HttpResponse(html_template.render(context, request))


@login_required(login_url="/login/")
def pages(request):
    context = {}
    # All resource paths end in .html.
    # Pick out the html file name from the url. And load that template.
    try:

        load_template = request.path.split('/')[-1]

        if load_template == 'admin':
            return HttpResponseRedirect(reverse('admin:index'))
        context['segment'] = load_template

        html_template = loader.get_template('home/' + load_template)
        return HttpResponse(html_template.render(context, request))

    except template.TemplateDoesNotExist:

        html_template = loader.get_template('home/page-404.html')
        return HttpResponse(html_template.render(context, request))

    except:
        html_template = loader.get_template('home/page-500.html')
        return HttpResponse(html_template.render(context, request))

bank/views.py
import json
from .models import TransactionHistory
from django.views.decorators.http import require_POST
from midtransclient import Snap
from .models import Application
from django.shortcuts import render, redirect
from decimal import Decimal
from pyexpat.errors import messages
import uuid
from django.db import IntegrityError
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import user_passes_test, login_required
from django.views.decorators.csrf import csrf_exempt  # Add this line
from .models import Application, BankAccount, BankAdmin, TransactionHistory

# handle login register for bank admin


@csrf_exempt
def register_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        try:
            user = User.objects.create_user(
                username=username, password=password)
            user.save()
            bank_admin = BankAdmin.objects.create(user=user)
            bank_admin.save()
            return redirect('bank:login')
        except IntegrityError:
            messages.error(
                request, 'Username already exists. Please choose a different username.')
            return redirect('bank:register')
        except Exception as e:
            # Log the error for debugging purposes
            print(f"Error creating user: {e}")
            messages.error(
                request, 'An unexpected error occurred. Please try again.')
            return redirect('bank:register')
    return render(request, 'homes/register.html', {})


@csrf_exempt
def login_bank_admin(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('bank:home')
    return render(request, 'homes/login.html')


# Handle user application

def show_applications(request, user_id):
    if request.method == 'POST':
        name = request.POST.get('name')
        ktp = request.FILES.get('ktp')
        if name:
            application = Application(
                name=name, ktp_photo=ktp, user_id=user_id)
            bank_account = BankAccount(
                name=name, ktp_photo=ktp, user_id=user_id)
            bank_account.save()
            application.bank_account = bank_account
            application.save()
            return redirect('bank:apply', user_id=user_id)
    application = Application.objects.using('bank').all()
    return render(request, 'application.html', {'application': application, 'user_id': user_id})


def topup(request, user_id):
    return render(request, 'topup.html', {'user_id': user_id})
# Handle user transaction with bank
# @require_POST


def create_transaction(request, user_id):
    gross_amount = request.POST.get('gross_amount')
    snap = Snap(
        is_production=False,
        server_key='SB-Mid-server-OUOnIHlPonXlJ3zt7M8mQkGX',
        client_key='SB-Mid-client-zF1Nl-didCEzFYUM'
    )
    order_id = str(uuid.uuid4())

    param = {
        "transaction_details": {
            "order_id": order_id,
            "gross_amount": gross_amount,
        },
        "credit_card": {
            "secure": True
        }
    }

    transaction = snap.create_transaction(param)
    print(transaction)
    bank_account = BankAccount.objects.get(user_id=user_id)
    bank_account.balance += Decimal(gross_amount)
    bank_account.save()
    TransactionHistory.objects.create(
        source_account=BankAccount.objects.get(user_id=user_id),
        destination_account=BankAccount.objects.get(user_id=user_id),
        transaction_type='D',
        amount=gross_amount
    )
    return redirect(transaction['redirect_url'])


# handle transaction between users


def index_views(request):
    if request.method == 'POST':
        application_id = request.POST.get('application_id')
        application_status = request.POST.get('status')
        application = Application.objects.get(id=application_id)
        application.status = application_status
        if application_status == 'A':
            bank_account = application.bank_account
            bank_account.is_active = True
            bank_account.save()
        application.save()
        return redirect('bank:home')
    applications = Application.objects.using('bank').all().order_by('-status')
    transactions = TransactionHistory.objects.using(
        'bank').all().order_by('-transaction_date')

    return render(request, 'tables.html', {'applications': applications, 'transactions': transactions})


@require_POST
def handle_transaction(request):
    # Get the source and destination account IDs from the POST data
    source_account_id = request.POST.get('source_account_id')
    destination_account_id = request.POST.get('destination_account_id')

    # Get the transaction amount from the POST data
    amount = request.POST.get('amount')

    # Get the source and destination accounts from the database
    source_account = get_object_or_404(BankAccount, user_id=source_account_id)
    destination_account = get_object_or_404(
        BankAccount, user_id=destination_account_id)

    # Check if the source account has enough balance for the transaction
    if source_account.balance < amount:
        return HttpResponse('Insufficient balance', status=400)

    # Deduct the amount from the source account's balance
    source_account.balance -= amount
    source_account.save()

    # Add the amount to the destination account's balance
    destination_account.balance += amount
    destination_account.save()

    # Create a new transaction history
    TransactionHistory.objects.create(
        source_account=source_account,
        destination_account=destination_account,
        transaction_type='P',
        amount=amount,
    )

    return HttpResponse('Transaction successful', status=200)

bank/templates/application.html
<!DOCTYPE html>
<html>
<head>
    <title>Application Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
      <div class="h-screen bg-gray-100 flex justify-center">
    <div class="py-6 px-8 h-80 mt-20 bg-white rounded shadow-xl">
      <form method="POST" action="{% url 'bank:apply' user_id=user_id %}" enctype="multipart/form-data">
        <h1 class="font-bold text-center">Application Form</h1>
        {% csrf_token %}
        <div class="mb-6">
          <label for="name" class="block text-gray-800 font-bold">Name:</label>
          <input type="text" name="name" id="name" placeholder="username" class="w-full border border-gray-300 py-2 pl-3 rounded mt-2 outline-none focus:ring-indigo-600 :ring-indigo-600" />
        </div>

        <div>
          <label for="ktp" class="block text-gray-800 font-bold">Your KTP:</label>
          {% comment %} <input type="file" name="ktp" id="ktp" class="w-full border border-gray-300 py-2 pl-3 rounded mt-2 outline-none focus:ring-indigo-600 :ring-indigo-600" /> {% endcomment %}
          <input type="file" id="ktp" name="ktp"><br>
        </div>
        <button type="submit" class="cursor-pointer py-2 px-4 block mt-6 bg-indigo-500 text-white font-bold w-full text-center rounded">Register</button>
      </form>
    </div>
  </div>
</body>
</html>

bank/templates/form.html
<!DOCTYPE html>
<html>
<head>
    <title>Application Page</title>
</head>
<body>
    <h1>Application Form</h1>
    <form method="POST" action="{% url 'bank:apply' user_id=12345 %}" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="name">Name:</label><br>
        <input type="text" id="name" name="name"><br>
        <label for="ktp">KTP Photo:</label><br>
        <input type="file" id="ktp" name="ktp"><br>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

bank/templates/tables.html
{% extends 'layout/base.html' %}

{% block title %} Tables {% endblock title %}

{% block content %}

<div class="header bg-primary pb-6">
  <div class="container-fluid">
    <div class="header-body">
      <div class="row align-items-center py-4">
        <div class="col-lg-6 col-7">
          <h6 class="h2 text-white d-inline-block mb-0">Dashboard</h6>
          <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
              <li class="breadcrumb-item"><a href="#"><i class="fas fa-home"></i></a></li>
              <li class="breadcrumb-item"><a href="#">Bank</a></li>
              <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
            </ol>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Page content -->
<div class="container-fluid mt--6">
  <div class="row">
    <div class="col">
      <div class="card">
        <!-- Card header -->
        <div class="card-header border-0">
          <h3 class="mb-0">Applications Data</h3>
        </div>
        <!-- Light table -->
        <div class="table-responsive">
          <table class="table align-items-center table-flush">
            <thead class="thead-light">
              <tr>
                <th scope="col" class="sort" data-sort="name">Nama</th>
                {% comment %}
                <!-- <th scope="col" class="sort" data-sort="photo">Foto KTP</th> -->
                {% endcomment %}
                <th scope="col" class="sort" data-sort="status">Status</th>
                <th scope="col" class="sort" data-sort="completion">Action Status</th>
                <th scope="col" class="sort" data-sort="completion">Applied At</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody class="list">
              {% for application in applications %}
              <tr>
                <th scope="row">
                  <div class="media align-items-center">
                    <div class="media-body">
                      <span class="name mb-0 text-sm">{{application.name}}</span>
                    </div>
                  </div>
                </th>
                {% comment %}
                <!-- <td class="photo">
                    <a class="" href="{{application.ktp_photo.url}}">{{application.ktp_photo|truncatechars:20}}</a>
                  </td> -->
                {% endcomment %}
                <td>
                  <span class="badge badge-dot mr-4">
                    {% if application.status == 'P' %}
                    <i class="bg-warning"></i>
                    <span class="status">Pending</span>
                    {% elif application.status == 'A' %}
                    <i class="bg-success"></i>
                    <span class="status">Accepted</span>
                    {% elif application.status == 'D' %}
                    <i class="bg-danger"></i>
                    <span class="status">Declined</span>
                    {% endif %}
                  </span>
                </td>
                <td>
                  <div class=" d-flex">
                    <form method="POST" action="{% url 'bank:home' %}" class="mr-2">
                      {% csrf_token %}
                      <input type="hidden" name="application_id" value="{{application.id}}">
                      <input type="hidden" name="status" value="D">
                      <input type="submit" class="btn btn-sm btn-neutral" value="Decline">
                    </form>
                    <form method="POST" action="{% url 'bank:home' %}" class="">
                      {% csrf_token %}
                      <input type="hidden" name="application_id" value="{{application.id}}">
                      <input type="hidden" name="status" value="A">
                      <input type="submit" class="btn btn-sm btn-neutral" value="Accept">
                    </form>
                    {% comment %} <a href="#" class="btn btn-sm btn-neutral">Reject</a>
                    <a href="#" class="btn btn-sm btn-neutral">Accept</a> {% endcomment %}
                </td>
                <td class="">
                  <div class="media align-items-center">
                    <div class="media-body">
                      <span class="name mb-0 text-sm">{{application.applied_at}}</span>
                    </div>
                  </div>
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
        <!-- Card footer -->
        <div class="card-footer py-4">
          <nav aria-label="...">
          </nav>
        </div>
      </div>
    </div>
  </div>
  <!-- Dark table -->
  <div class="row">
    <div class="col">
      <div class="card bg-default shadow">
        <div class="card-header bg-0">
          <h3 class="mb-0">Payment Data</h3>
        </div>
        <div class="table-responsive">
          <table class="table align-items-center table-white table-flush">
            <thead class="thead-white">
              <tr>
                <th scope="col" class="sort" data-sort="name">Pengirim</th>
                <th scope="col" class="sort" data-sort="photo">Penerima</th>
                <th scope="col" class="sort" data-sort="jumlah">Jumlah</th>
                <th scope="col" class="sort" data-sort="status">Tipe</th>
                <th scope="col" class="sort" data-sort="status">Tanggal</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody class="list">
              {% for transaction in transactions %}
              <tr>
                <th scope="row">
                  <div class="media align-items-center">
                    <div class="media-body">
                      <span class="name mb-0 text-sm">{{transaction.source_account|truncatechars:20}}</span>
                    </div>
                  </div>
                </th>
                <th scope="row">
                  <div class="media align-items-center">
                    <div class="media-body">
                      <span class="name mb-0 text-sm">{{transaction.destination_account|truncatechars:20}}</span>
                    </div>
                  </div>
                </th>
                <td class="photo">
                  {{transaction.amount}}
                </td>
                <td>
                  <span class="badge badge-dot mr-4">
                    {% if transaction.transaction_type == 'D' %}
                    <span class="status">Deposit</span>
                    {% elif transaction.transaction_type == 'W' %}
                    <span class="status">Withdraw</span>
                    {% elif transaction.transaction_type == 'T'%}
                    <span class="status">Transfer</span>
                    {% endif %}
                  </span>
                </td>
                <td>
                  <span class="badge badge-dot mr-4">
                    <span class="status">{{transaction.transaction_date}}</span>
                  </span>
                </td>
              </tr>
              {% endfor %}

            </tbody>
          </table>
          <!-- Card footer -->
          <div class="card-footer py-4">
            <nav aria-label="...">
              {% comment %} <ul class="pagination justify-content-end mb-0">
                <li class="page-item disabled">
                  <a class="page-link" href="#" tabindex="-1">
                    <i class="fas fa-angle-left"></i>
                    <span class="sr-only">Previous</span>
                  </a>
                </li>
                <li class="page-item active">
                  <a class="page-link" href="#">1</a>
                </li>
                <li class="page-item">
                  <a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
                </li>
                <li class="page-item"><a class="page-link" href="#">3</a></li>
                <li class="page-item">
                  <a class="page-link" href="#">
                    <i class="fas fa-angle-right"></i>
                    <span class="sr-only">Next</span>
                  </a> {% endcomment %}
                </li>
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>

  {% include "include/footer.html" %}

</div>

{% endblock content %}

<!-- Specific JS goes HERE -->
{% block javascripts %}{% endblock javascripts %}

bank/templates/topup.html
<!DOCTYPE html>
<html>
<head>
    <title>Application Page</title>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
      <div class="h-screen bg-gray-100 flex justify-center">
    <div class="py-6 px-8 h-80 mt-20 bg-white rounded shadow-xl">
        <h1 class="font-bold text-center text-2xl">Top Up Form</h1>
        <br>
      <form method="POST" action="{% url 'bank:create' user_id=user_id %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="mb-6">
          <label for="name" class="block text-gray-800 font-bold">How much would you topup:</label>
          <input type="number" name="gross_amount" id="gross_amount" placeholder="" class="w-full border border-gray-300 py-2 pl-3 rounded mt-2 outline-none focus:ring-indigo-600 :ring-indigo-600" />
        </div>
        <button type="submit" class="cursor-pointer py-2 px-4 block mt-6 bg-indigo-500 text-white font-bold w-full text-center rounded">Top Up</button>
      </form>
    </div>
  </div>
</body>
</html>